GET http://localhost:8080/api/articles/places/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJST0xFIjoiUk9MRV9VU0VSIiwiTE9HSU5fRU1BSUwiOiJzb2FyX2R5QG5hdmVyLmNvbSIsImlzcyI6Im9vZXVueiIsIkdFTkRFUiI6IldPTUFOIiwiTEFOR1UiOiJLT1IifQ.necEBKSJMj5V96GlqvritrPW4JpGG8UnrrDWoHU8xLE

###
