GET http://localhost:8080/api/articles/1/reviews
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJST0xFIjoiUk9MRV9VU0VSIiwiTE9HSU5fRU1BSUwiOiJzb2FyX2R5QG5hdmVyLmNvbSIsImlzcyI6Im9vZXVueiIsIkdFTkRFUiI6IldPTUFOIiwiTUVNQkVSX0lEIjo1LCJMQU5HVSI6IktPUiJ9.dBT46jFXI9q3McYeqaDEAn8z6d_xBhTVQX6S6aHDvR4

###